In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[5.6118e-37, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 4.5872e-41],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 3.8773e+36]])


In [4]:
torch.zeros(3, 5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

Construct a randomly initialized matrix:



In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9951, 0.9978, 0.7367],
        [0.8085, 0.7937, 0.4284],
        [0.2293, 0.6867, 0.8480],
        [0.2688, 0.2198, 0.7014],
        [0.7446, 0.5930, 0.1247]])


Construct a matrix filled zeros and of dtype long:



In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = torch.tensor([[5.5, 3], [3, 4]],  dtype=torch.int)
print(x)

tensor([[5, 3],
        [3, 4]], dtype=torch.int32)


In [9]:
x = torch.tensor([[5.5, 3], [3, 4]],  dtype=torch.float32)
print(x)

tensor([[5.5000, 3.0000],
        [3.0000, 4.0000]])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [10]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.3323,  1.5085,  0.0999],
        [ 0.9795,  0.6672,  0.4700],
        [ 0.1698, -1.2194,  0.3067],
        [ 1.7563,  0.6906,  0.4397],
        [ 0.1558,  0.5634, -0.6025]])


Get its size:



In [11]:
print(x.size())

torch.Size([5, 3])


In [12]:
# or using shape:
x.shape

torch.Size([5, 3])

<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [13]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.0382,  1.8285,  0.6466],
        [ 1.4094,  1.1339,  0.5593],
        [ 0.7823, -0.4130,  1.1867],
        [ 2.6239,  0.9500,  0.9050],
        [ 0.3320,  1.4925,  0.1037]])


Addition: syntax 2



In [14]:
print(torch.add(x, y))

tensor([[-0.0382,  1.8285,  0.6466],
        [ 1.4094,  1.1339,  0.5593],
        [ 0.7823, -0.4130,  1.1867],
        [ 2.6239,  0.9500,  0.9050],
        [ 0.3320,  1.4925,  0.1037]])


Addition: providing an output tensor as argument



In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.0382,  1.8285,  0.6466],
        [ 1.4094,  1.1339,  0.5593],
        [ 0.7823, -0.4130,  1.1867],
        [ 2.6239,  0.9500,  0.9050],
        [ 0.3320,  1.4925,  0.1037]])


Addition: in-place



In [16]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.0382,  1.8285,  0.6466],
        [ 1.4094,  1.1339,  0.5593],
        [ 0.7823, -0.4130,  1.1867],
        [ 2.6239,  0.9500,  0.9050],
        [ 0.3320,  1.4925,  0.1037]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [17]:
x[0]

tensor([-0.3323,  1.5085,  0.0999])

In [18]:
print(x[:, 1])

tensor([ 1.5085,  0.6672, -1.2194,  0.6906,  0.5634])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [19]:
x = torch.randn(4, 4)
y = x.view(16) # same as x.reshape(-1)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [20]:
x = torch.randn(1)
print(x)
print(x.item())

# another example:
q = torch.randn(2, 2)[1][0].item()
print(q)

tensor([-0.9950])
-0.9950258135795593
-1.695307970046997


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [21]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [22]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [23]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [24]:
# If you want to avoid such dependence:
b = a.numpy().copy()
print(b)

a.add_(1)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [25]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [38]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([0.0050], device='cuda:0')
tensor([0.0050], dtype=torch.float64)
